### ISSUE TITLE
comtypes: not a valid filename

### ISSUE THREAD

**Issue by NarenZen** [natter1/python_pptx_interface#5]
@natter1 I'm using the **save_pptx_as_png** function

In this line `pres.SaveAs(str(save_folder), pp_constants.ppSaveAsPNG)`
I'm getting the below error.

My save path is C:/Users/naren/Music/imgs/ , so giving it as 
`pres.SaveAs("C:/Users/naren/Music/imgs/", pp_constants.ppSaveAsPNG)`

```
pres.SaveAs("C:/Users/naren/Music/imgs/", pp_constants.ppSaveAsPNG)                                                
_ctypes.COMError: (-2147188160, None, ('Presentation (unknown member) : Invalid request.  This is not a valid filename.', 'Microsoft PowerPoint', '', 0, None))  
```

**Comment by natter1** [comment]
Hmm, this messages is from PowerPoint. I think there might be an issue with your save path string. Can you try to replace '/' with '\\\\' (or '\\')?
Also, does the path already exist?

**Comment by NarenZen** [comment]
@natter1 I tried with "\\" and "\". Both options didn't help me.
Yes the path already exists(empty dir).

**Comment by natter1** [comment]
Can you try a Path thats not a windows special path? Something like "c://test//imgs//"?

**Comment by NarenZen** [comment]
fixed the problem

It should be 
`C:\\Users\\naren\\Music\\imgs`

not
`C:\\Users\\naren\\Music\\imgs\\`

Thanks @natter1
